SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS activities;
DROP TABLE IF EXISTS activity_stages;
DROP TABLE IF EXISTS administrators;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS moment_comments;
DROP TABLE IF EXISTS moments;
DROP TABLE IF EXISTS organization_departments;
DROP TABLE IF EXISTS organization_honors;
DROP TABLE IF EXISTS organizations;
DROP TABLE IF EXISTS photo_lives;
DROP TABLE IF EXISTS photo_lives_supervisors;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS provinces;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS users_follow_activities;
DROP TABLE IF EXISTS users_follow_organizations;
DROP TABLE IF EXISTS users_follow_users;
DROP TABLE IF EXISTS users_like_moments;
DROP TABLE IF EXISTS users_participate_organizations;
DROP TABLE IF EXISTS users_sign_activities;
SET FOREIGN_KEY_CHECKS = 1;
