SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE activities;
TRUNCATE TABLE activity_stages;
TRUNCATE TABLE administrators;
TRUNCATE TABLE cities;
TRUNCATE TABLE moment_comments;
TRUNCATE TABLE moments;
TRUNCATE TABLE organization_departments;
TRUNCATE TABLE organization_honors;
TRUNCATE TABLE organizations;
TRUNCATE TABLE photo_lives;
TRUNCATE TABLE photo_lives_supervisors;
TRUNCATE TABLE photos;
TRUNCATE TABLE provinces;
TRUNCATE TABLE users;
TRUNCATE TABLE users_follow_activities;
TRUNCATE TABLE users_follow_organizations;
TRUNCATE TABLE users_follow_users;
TRUNCATE TABLE users_like_moments;
TRUNCATE TABLE users_participate_organizations;
TRUNCATE TABLE users_sign_activities;
SET FOREIGN_KEY_CHECKS = 1;
