SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE activities;
TRUNCATE TABLE activity_stages;
TRUNCATE TABLE administrator_login_logs;
TRUNCATE TABLE administrators;
TRUNCATE TABLE organizations_contactors;
TRUNCATE TABLE organization_departments;
TRUNCATE TABLE organization_login_logs;
TRUNCATE TABLE organizations;
TRUNCATE TABLE photo_comments;
TRUNCATE TABLE photo_lives;
TRUNCATE TABLE photo_lives_supervisors;
TRUNCATE TABLE photos;
TRUNCATE TABLE photo_tags;
TRUNCATE TABLE users_activities;
TRUNCATE TABLE user_login_logs;
TRUNCATE TABLE users_organizations;
TRUNCATE TABLE users_photos;
TRUNCATE TABLE users;
TRUNCATE TABLE users_users;
SET FOREIGN_KEY_CHECKS = 1;