SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE activities;
TRUNCATE TABLE activity_stages;
TRUNCATE TABLE administrator_login_logs;
TRUNCATE TABLE administrators;
TRUNCATE TABLE organization_contact_relationships;
TRUNCATE TABLE organization_departments;
TRUNCATE TABLE organization_login_logs;
TRUNCATE TABLE organizations;
TRUNCATE TABLE photo_comments;
TRUNCATE TABLE photo_lives;
TRUNCATE TABLE photo_live_supervisor_relationships;
TRUNCATE TABLE photos;
TRUNCATE TABLE photo_tags;
TRUNCATE TABLE user_activity_relationships;
TRUNCATE TABLE user_login_logs;
TRUNCATE TABLE user_organization_relationships;
TRUNCATE TABLE user_photo_relationships;
TRUNCATE TABLE users;
TRUNCATE TABLE user_user_relationships;
SET FOREIGN_KEY_CHECKS = 1;